### ISSUE TITLE
Repeat Elements (REs) GREAT analysis 

### ISSUE THREAD

**Issue by Irinalazar** [mansuylab/SC_postnatal_adult#40]
#25  @dktanwar 
We have performed HOMER using the class as a background (eg: all LTRs, all SINEs). It would be good to perform GREAT similarly (now we either have run GREAT on all identified REs or on all diff access REs). I would need: 

- [x] GREAT analysis on Categories 1-6 using class as a background (the excel sheet with the categories you should already have, but if not let me now and I can resend it). 

Eg: Category 1 (less access ERV1 subtypes ran against all identified LTRs); Category 2 (less access ERVK subtypes ran against all identified LTRs); Category 5 (more access ERVK subtypes ran against all LTRs); Category 6 (more access L1 subtypes ran against all identified LINEs) etc....

**Comment by dktanwar** [comment]
It should go under #25 , so, I copied it there
